sudo: required
dist: xenial
language: cpp
before_install:
  - sudo apt-get update; true
before_script:
  - travis_wait 30 sudo -i -E perl $TRAVIS_BUILD_DIR/src/fastnetmon_install.pl --use-git-master --api --gobgp
  - cd $TRAVIS_BUILD_DIR/src
script: mkdir -p build; cd build; cmake ..; make
notifications:
  email:
    recipients:
      - pavel.odintsov@gmail.com
    on_success: change
    on_failure: always
matrix:
  include:
  - dist: trusty
    os: linux
    compiler: gcc
  - dist: xenial
    os: linux
    compiler: gcc
  - dist: bionic
    os: linux
    compiler: gcc
