version: 2.1
jobs:
  ubuntu2004:
    docker:
      - image: ubuntu:focal-20200423
    steps:
      - checkout
      - run: apt-get update; true
      - run: apt-get install -y perl wget
      - run:
          name: install_required_packages
          no_output_timeout: 20m
          command: perl src/fastnetmon_install.pl --install_dependency_packages_only
      - restore_cache:
          keys:
            - "{{ .Environment.CIRCLE_JOB }}_dependencies_26_05_2020"
      - run:
          name: install_dependencies
          no_output_timeout: 35m
          command: perl src/fastnetmon_install.pl --use-git-master -api --gobgp
      - run:
          name: collect_debug
          command: cat /tmp/fastnetmon_install.log
          when: on_fail
      - save_cache:
          key: "{{ .Environment.CIRCLE_JOB }}_dependencies_26_05_2020"
          paths:
            - /opt
      - run: cd src; mkdir -p build; cd build; cmake ..; make
      - run: /opt/fastnetmon/fastnetmon --configuration_check  
  ubuntu1804:
    docker:
      - image: ubuntu:bionic-20200403
    steps:
      - checkout
      - run: apt-get update; true
      - run: apt-get install -y perl wget
      - run:
          name: install_required_packages
          no_output_timeout: 20m
          command: perl src/fastnetmon_install.pl --install_dependency_packages_only
      - restore_cache:
          keys:
            - "{{ .Environment.CIRCLE_JOB }}_dependencies_26_05_2020"
      - run:
          name: install_dependencies
          no_output_timeout: 35m
          command: perl src/fastnetmon_install.pl --use-git-master -api --gobgp
      - run:
          name: collect_debug
          command: cat /tmp/fastnetmon_install.log
          when: on_fail
      - save_cache:
          key: "{{ .Environment.CIRCLE_JOB }}_dependencies_26_05_2020"
          paths:
            - /opt
      - run: cd src; mkdir -p build; cd build; cmake ..; make
      - run: /opt/fastnetmon/fastnetmon --configuration_check
  ubuntu1604:
    docker:
      - image: ubuntu:xenial-20200326
    steps:
      - checkout
      - run: apt-get update; true
      - run: apt-get install -y perl wget
      - run:
          name: install_required_packages
          no_output_timeout: 20m
          command: perl src/fastnetmon_install.pl --install_dependency_packages_only
      - restore_cache:
          keys:
            - "{{ .Environment.CIRCLE_JOB }}_dependencies_26_05_2020"
      - run:
          name: install_dependencies
          no_output_timeout: 35m
          command: perl src/fastnetmon_install.pl --use-git-master -api --gobgp
      - run:
          name: collect_debug
          command: cat /tmp/fastnetmon_install.log
          when: on_fail
      - save_cache:
          key: "{{ .Environment.CIRCLE_JOB }}_dependencies_26_05_2020"
          paths:
            - /opt
      - run: cd src; mkdir -p build; cd build; cmake ..; make
      - run: /opt/fastnetmon/fastnetmon --configuration_check
  ubuntu1404:
    docker:
      - image: ubuntu:trusty-20191217
    steps:
      - checkout
      - run: apt-get update; true
      - run: apt-get install -y perl wget
      - run:
          name: install_required_packages
          no_output_timeout: 20m
          command: perl src/fastnetmon_install.pl --install_dependency_packages_only
      - restore_cache:
          keys:
            - "{{ .Environment.CIRCLE_JOB }}_dependencies_26_05_2020"
      - run:
          name: install_dependencies
          no_output_timeout: 35m
          command: perl src/fastnetmon_install.pl --use-git-master -api --gobgp
      - run:
          name: collect_debug
          command: cat /tmp/fastnetmon_install.log
          when: on_fail
      - save_cache:
          key: "{{ .Environment.CIRCLE_JOB }}_dependencies_26_05_2020"
          paths:
            - /opt
      - run: cd src; mkdir -p build; cd build; cmake ..; make
      - run: /opt/fastnetmon/fastnetmon --configuration_check
  debian8:
    docker:
      - image: debian:jessie-20200514
    steps:
      - checkout
      - run: apt-get update; true
      - run: apt-get install -y perl wget
      - run:
          name: install_required_packages
          no_output_timeout: 35m
          command: perl src/fastnetmon_install.pl --install_dependency_packages_only
      - restore_cache:
          keys:
            - "{{ .Environment.CIRCLE_JOB }}_dependencies_26_05_2020"
      - run:
          name: install_dependencies
          no_output_timeout: 20m
          command: perl src/fastnetmon_install.pl --use-git-master -api --gobgp
      - run:
          name: collect_debug
          command: cat /tmp/fastnetmon_install.log
          when: on_fail
      - save_cache:
          key: "{{ .Environment.CIRCLE_JOB }}_dependencies_26_05_2020"
          paths:
            - /opt
      - run: cd src; mkdir -p build; cd build; cmake ..; make
      - run: /opt/fastnetmon/fastnetmon --configuration_check
  debian9:
    docker:
      - image: debian:stretch-20200514
    steps:
      - checkout
      - run: apt-get update; true
      - run: apt-get install -y perl wget
      - run:
          name: install_required_packages
          no_output_timeout: 35m
          command: perl src/fastnetmon_install.pl --install_dependency_packages_only
      - restore_cache:
          keys:
            - "{{ .Environment.CIRCLE_JOB }}_dependencies_26_05_2020"
      - run:
          name: install_dependencies
          no_output_timeout: 20m
          command: perl src/fastnetmon_install.pl --use-git-master -api --gobgp
      - run:
          name: collect_debug
          command: cat /tmp/fastnetmon_install.log
          when: on_fail
      - save_cache:
          key: "{{ .Environment.CIRCLE_JOB }}_dependencies_26_05_2020"
          paths:
            - /opt
      - run: cd src; mkdir -p build; cd build; cmake ..; make
      - run: /opt/fastnetmon/fastnetmon --configuration_check
  debian10:
    docker:
      - image: debian:buster-20200514
    steps:
      - checkout
      - run: apt-get update; true
      - run: apt-get install -y perl wget
      - run:
          name: install_required_packages
          no_output_timeout: 20m
          command: perl src/fastnetmon_install.pl --install_dependency_packages_only
      - restore_cache:
          keys:
            - "{{ .Environment.CIRCLE_JOB }}_dependencies_26_05_2020"
      - run:
          name: install_dependencies
          no_output_timeout: 35m
          command: perl src/fastnetmon_install.pl --use-git-master -api --gobgp
      - run:
          name: collect_debug
          command: cat /tmp/fastnetmon_install.log
          when: on_fail
      - save_cache:
          key: "{{ .Environment.CIRCLE_JOB }}_dependencies_26_05_2020"
          paths:
            - /opt
      - run: cd src; mkdir -p build; cd build; cmake ..; make
      - run: /opt/fastnetmon/fastnetmon --configuration_check
  centos6:
    docker:
      - image: centos:centos6.9
    steps:
      - checkout
      - run: yum install -y perl wget
      - run:
          name: install_required_packages
          no_output_timeout: 20m
          command: perl src/fastnetmon_install.pl --install_dependency_packages_only
      - restore_cache:
          keys:
            - "{{ .Environment.CIRCLE_JOB }}_dependencies_27_05_2020"
      - run:
          name: install_dependencies
          no_output_timeout: 20m
          command: perl src/fastnetmon_install.pl --use-git-master
      - run:
          name: collect_debug
          command: cat /tmp/fastnetmon_install.log
          when: on_fail
      - save_cache:
          key: "{{ .Environment.CIRCLE_JOB }}_dependencies_27_05_2020"
          paths:
            - /opt
            - /usr/include/linux/pf_ring.h
      - run: cd src; mkdir -p build; cd build; cmake ..; make
      - run: /opt/fastnetmon/fastnetmon --configuration_check
  centos7:
    docker:
      - image: centos:centos7.8.2003
    steps:
      - checkout
      - run: yum install -y perl wget
      - run:
          name: install_required_packages
          no_output_timeout: 20m
          command: perl src/fastnetmon_install.pl --install_dependency_packages_only
      - restore_cache:
          keys:
            - "{{ .Environment.CIRCLE_JOB }}_dependencies_26_05_2020"
      - run:
          name: install_dependencies
          no_output_timeout: 35m
          command: perl src/fastnetmon_install.pl --use-git-master -api --gobgp
      - run:
          name: collect_debug
          command: cat /tmp/fastnetmon_install.log
          when: on_fail
      - save_cache:
          key: "{{ .Environment.CIRCLE_JOB }}_dependencies_26_05_2020"
          paths:
            - /opt
      - run: cd src; mkdir -p build; cd build; cmake ..; make
      - run: /opt/fastnetmon/fastnetmon --configuration_check
  centos8:
    docker:
      - image: centos:centos8.1.1911
    steps:
      - checkout
      - run: yum install -y perl wget
      - run:
          name: install_required_packages
          no_output_timeout: 20m
          command: perl src/fastnetmon_install.pl --install_dependency_packages_only
      - run:
          name: collect_debug
          command: cat /tmp/fastnetmon_install.log
          when: on_fail
      - restore_cache:
          keys:
            - "{{ .Environment.CIRCLE_JOB }}_dependencies_26_05_2020"
      - run:
          name: install_dependencies
          no_output_timeout: 35m
          command: perl src/fastnetmon_install.pl --use-git-master -api --gobgp
      - save_cache:
          key: "{{ .Environment.CIRCLE_JOB }}_dependencies_26_05_2020"
          paths:
            - /opt
      - run: cd src; mkdir -p build; cd build; cmake ..; make
      - run: /opt/fastnetmon/fastnetmon --configuration_check
workflows:
  version: 2
  all_distros:
    jobs:
      - debian8
      - debian9
      - debian10
      - ubuntu1404
      - ubuntu1604
      - ubuntu1804
      - ubuntu2004
      - centos6
      - centos7
      - centos8
