version: 2
jobs:
  ubuntu2004:
    docker:
      - image: ubuntu:focal-20200423
    steps:
      - checkout
      - run: apt-get update; true
      - run: apt-get install -y perl wget
      - run: perl src/fastnetmon_install.pl --use-git-master
      - run: cd src; mkdir -p build; cd build; cmake ..; make
workflows:
  version: 2
  all_distros:
    jobs:
      - ubuntu2004
