version: 2
jobs:
  ubuntu2004:
    docker:
      - image: ubuntu:focal-20200423
    steps:
      - checkout
      - run: apt-get update; true
      - run: apt-get install -y perl wget
      - run:
          name: install_required_packages
          no_output_timeout: 20m
          command: perl src/fastnetmon_install.pl --install_dependency_packages_only
      - restore_cache:
          keys:
            - ubuntu2004_dependencies_25_05_2020
      - run:
          name: install_dependencies
          no_output_timeout: 20m
          command: perl src/fastnetmon_install.pl --use-git-master
      - save_cache:
          key: ubuntu2004_dependencies_25_05_2020
          paths:
            - /opt
      - run: cd src; mkdir -p build; cd build; cmake ..; make 
  ubuntu1804:
    docker:
      - image: ubuntu:bionic-20200403
    steps:
      - checkout
      - run: apt-get update; true
      - run: apt-get install -y perl wget
      - run:
          name: install_required_packages
          no_output_timeout: 20m
          command: perl src/fastnetmon_install.pl --install_dependency_packages_only
      - restore_cache:
          keys:
            - ubuntu1804_dependencies_25_05_2020
      - run:
          name: install_dependencies
          no_output_timeout: 20m
          command: perl src/fastnetmon_install.pl --use-git-master
      - save_cache:
          key: ubuntu1804_dependencies_25_05_2020
          paths:
            - /opt
      - run: cd src; mkdir -p build; cd build; cmake ..; make
  ubuntu1604:
    docker:
      - image: ubuntu:xenial-20200326
    steps:
      - checkout
      - run: apt-get update; true
      - run: apt-get install -y perl wget
      - run:
          name: install_required_packages
          no_output_timeout: 20m
          command: perl src/fastnetmon_install.pl --install_dependency_packages_only
      - restore_cache:
          keys:
            - ubuntu1604_dependencies_25_05_2020
      - run:
          name: install_dependencies
          no_output_timeout: 20m
          command: perl src/fastnetmon_install.pl --use-git-master
      - save_cache:
          key: ubuntu1604_dependencies_25_05_2020
          paths:
            - /opt
      - run: cd src; mkdir -p build; cd build; cmake ..; make
  debian9:
    docker:
      - image: debian:stretch-20200514
    steps:
      - checkout
      - run: apt-get update; true
      - run: apt-get install -y perl wget
      - run:
          name: install_required_packages
          no_output_timeout: 20m
          command: perl src/fastnetmon_install.pl --install_dependency_packages_only
      - restore_cache:
          keys:
            - debian9_dependencies_25_05_2020
      - run:
          name: install_dependencies
          no_output_timeout: 20m
          command: perl src/fastnetmon_install.pl --use-git-master
      - save_cache:
          key: debian9_dependencies_25_05_2020
          paths:
            - /opt
      - run: cd src; mkdir -p build; cd build; cmake ..; make
  debian10:
    docker:
      - image: debian:buster-20200514
    steps:
      - checkout
      - run: apt-get update; true
      - run: apt-get install -y perl wget
      - run:
          name: install_required_packages
          no_output_timeout: 20m
          command: perl src/fastnetmon_install.pl --install_dependency_packages_only
      - restore_cache:
          keys:
            - debian10_dependencies_25_05_2020
      - run:
          name: install_dependencies
          no_output_timeout: 20m
          command: perl src/fastnetmon_install.pl --use-git-master
      - save_cache:
          key: debian10_dependencies_25_05_2020
          paths:
            - /opt
      - run: cd src; mkdir -p build; cd build; cmake ..; make
workflows:
  version: 2
  all_distros:
    jobs:
      - debian9
      - debian10
      - ubuntu1604
      - ubuntu1804
      - ubuntu2004
