version: 2
jobs:
  ubuntu2004:
    docker:
      - image: ubuntu:focal-20200423
    steps:
      - checkout
      - run: apt-get update; true
      - run: apt-get install -y perl wget
      - run:
          name: install_required_packages
          no_output_timeout: 20m
          command: perl src/fastnetmon_install.pl --install_dependency_packages_only
      - restore_cache:
          keys:
            - ubuntu2004_dependencies_25_05_2020
      - run:
          name: install_dependencies
          no_output_timeout: 20m
          command: perl src/fastnetmon_install.pl --use-git-master
      - save_cache:
          key: ubuntu2004_dependencies_25_05_2020
          paths:
            - /opt
      - run: cd src; mkdir -p build; cd build; cmake ..; make
workflows:
  version: 2
  all_distros:
    jobs:
      - ubuntu2004
